# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gold Codes.
email: Lol
description: > # this means to ignore newlines until "baseurl:"
  I am a coder that is still learning the basics online but I hope to be a great coder someday
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goldcodes.github.io" # the base hostname & protocol for your site
twitter_username: goldb_
github_username:  GoldCodes

# Build settings
markdown: kramdown

gems:
  - jekyll-feed